
name: Node CI
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [16]
    steps:
    - uses: actions/checkout@master
#       uses: actions/setup-node@v3
    - name: npm install
      run: npm install
    - name: npm run dev
      run: npm run dev
